

spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.username=postgres
spring.datasource.password=8192031365p

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081